<template>
    <section>
        <div id="contact"></div>
        <h1 class="text-center font-bold py-6 text-3xl mt-20">Hire Us</h1>
        <p>here is hire us info</p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis eligendi, ad maiores totam ullam aliquam voluptatum voluptatibus accusantium, quas labore fugit a aliquid tenetur sapiente aut minus, facilis distinctio.</span><span>Quaerat, vero. Consectetur quisquam similique, tempore quo delectus, culpa doloremque possimus libero, nobis voluptates praesentium minus voluptatum necessitatibus beatae. Commodi, ullam cum sit cupiditate itaque harum! Deserunt placeat facere est?</span></p>
    </section>
</template>